# Generated by Django 5.1.6 on 2025-02-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=50)),
                ('co2', models.IntegerField()),
                ('temp', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('voc', models.IntegerField()),
                ('pm2p5', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pm1', models.FloatField()),
                ('pm4', models.FloatField()),
                ('timestamp', models.IntegerField()),
                ('version', models.CharField(max_length=50)),
            ],
        ),
    ]
