# Generated by Django 5.1.6 on 2025-02-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('a_current', models.FloatField()),
                ('a_voltage', models.FloatField()),
                ('a_act_power', models.FloatField()),
                ('a_aprt_power', models.FloatField()),
                ('a_pf', models.FloatField()),
                ('a_freq', models.FloatField()),
                ('b_current', models.FloatField()),
                ('b_voltage', models.FloatField()),
                ('b_act_power', models.FloatField()),
                ('b_aprt_power', models.FloatField()),
                ('b_pf', models.FloatField()),
                ('b_freq', models.FloatField()),
                ('c_current', models.FloatField()),
                ('c_voltage', models.FloatField()),
                ('c_act_power', models.FloatField()),
                ('c_aprt_power', models.FloatField()),
                ('c_pf', models.FloatField()),
                ('c_freq', models.FloatField()),
                ('total_current', models.FloatField()),
                ('total_act_power', models.FloatField()),
                ('total_aprt_power', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=50)),
                ('co2', models.IntegerField()),
                ('temp', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('voc', models.IntegerField()),
                ('pm2p5', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pm1', models.FloatField()),
                ('pm4', models.FloatField()),
                ('timestamp', models.IntegerField()),
                ('version', models.CharField(max_length=50)),
            ],
        ),
    ]
