# Generated by Django 5.1.6 on 2025-06-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualitydata',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='energydata',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='occupancydata',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='radardata',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
