# Generated by Django 5.1.6 on 2025-07-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0002_airqualitydata_action_energydata_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
