# Generated by Django 5.1.6 on 2025-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0003_rawsensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='quality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
