# Generated by Django 5.1.6 on 2025-07-11 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0005_alter_airqualitydata_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoRaAirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('model_id', models.CharField(blank=True, max_length=10, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('hcho', models.FloatField(blank=True, null=True)),
                ('co2', models.FloatField(blank=True, null=True)),
                ('tvoc', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lora_aq_data', to='server_api.sensor')),
            ],
        ),
    ]
