# Generated by Django 5.1.6 on 2025-07-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0006_loraairqualitydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSG01AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('co2', models.PositiveIntegerField()),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pm2p5', models.PositiveIntegerField()),
                ('pm10', models.PositiveIntegerField()),
                ('voc', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('version', models.CharField(default='LSG01', max_length=50)),
                ('quality', models.CharField(default='Unknown', max_length=20)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_api.sensor')),
            ],
        ),
        migrations.DeleteModel(
            name='LoRaAirQualityData',
        ),
    ]
