# Generated by Django 5.1.6 on 2025-07-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0007_lsg01airqualitydata_delete_loraairqualitydata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lsg01airqualitydata',
            name='pm10',
        ),
        migrations.RemoveField(
            model_name='lsg01airqualitydata',
            name='pm2p5',
        ),
        migrations.RemoveField(
            model_name='lsg01airqualitydata',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='lsg01airqualitydata',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='lsg01airqualitydata',
            name='version',
        ),
        migrations.RemoveField(
            model_name='lsg01airqualitydata',
            name='voc',
        ),
        migrations.AddField(
            model_name='lsg01airqualitydata',
            name='hcho',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsg01airqualitydata',
            name='pm25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsg01airqualitydata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsg01airqualitydata',
            name='tvoc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lsg01airqualitydata',
            name='co2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lsg01airqualitydata',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lsg01airqualitydata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
